"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const marketer_controller_1 = require("../controllers/marketer.controller");
const protected_middleware_1 = require("../middlewares/protected.middleware");
const allowedTo_middleware_1 = require("../middlewares/allowedTo.middleware");
const user_interface_1 = require("../interfaces/user/user.interface");
const validation_middleware_1 = require("../middlewares/validation.middleware");
const marketer_validator_1 = require("../validations/marketer.validator");
const marketerRouter = (0, express_1.Router)();
marketerRouter.route("/").get(protected_middleware_1.protectedMiddleware, (0, allowedTo_middleware_1.allowedTo)(user_interface_1.Role.RootAdmin, user_interface_1.Role.AdminA, user_interface_1.Role.AdminB), marketer_controller_1.getAllMarketers);
marketerRouter.route("/:id").get(protected_middleware_1.protectedMiddleware, (0, allowedTo_middleware_1.allowedTo)(user_interface_1.Role.RootAdmin, user_interface_1.Role.AdminA, user_interface_1.Role.AdminB), marketer_controller_1.getOneMarketer);
marketerRouter.route("/").post(protected_middleware_1.protectedMiddleware, (0, allowedTo_middleware_1.allowedTo)(user_interface_1.Role.RootAdmin, user_interface_1.Role.AdminA, user_interface_1.Role.AdminB), (0, validation_middleware_1.validate)(marketer_validator_1.MarketerCreateValidator), marketer_controller_1.createMarketer);
marketerRouter.route("/:id").put(protected_middleware_1.protectedMiddleware, (0, allowedTo_middleware_1.allowedTo)(user_interface_1.Role.RootAdmin, user_interface_1.Role.AdminA, user_interface_1.Role.AdminB), marketer_controller_1.updateMarketer);
marketerRouter.route("/:id").delete(protected_middleware_1.protectedMiddleware, (0, allowedTo_middleware_1.allowedTo)(user_interface_1.Role.RootAdmin, user_interface_1.Role.AdminA, user_interface_1.Role.AdminB), marketer_controller_1.deleteMarketer);
exports.default = marketerRouter;
