"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const offer_controller_1 = require("../controllers/offer.controller");
const protected_middleware_1 = require("../middlewares/protected.middleware");
const allowedTo_middleware_1 = require("../middlewares/allowedTo.middleware");
const user_interface_1 = require("../interfaces/user/user.interface");
const offer_validator_1 = require("../validations/offer.validator");
const validation_middleware_1 = require("../middlewares/validation.middleware");
const offerRouter = (0, express_1.Router)();
offerRouter.route("/").get(offer_controller_1.getAllOffers);
offerRouter.route("/:id").get(offer_controller_1.getOneOfferById);
offerRouter.route("/").post(protected_middleware_1.protectedMiddleware, (0, allowedTo_middleware_1.allowedTo)(user_interface_1.Role.RootAdmin, user_interface_1.Role.AdminA, user_interface_1.Role.AdminB), (0, validation_middleware_1.validate)(offer_validator_1.OfferCreateValidator), offer_controller_1.createOffer);
offerRouter.route("/:id").put(protected_middleware_1.protectedMiddleware, (0, allowedTo_middleware_1.allowedTo)(user_interface_1.Role.RootAdmin, user_interface_1.Role.AdminA, user_interface_1.Role.AdminB), (0, validation_middleware_1.validate)(offer_validator_1.OfferUpdateValidator), offer_controller_1.updateOffer);
offerRouter.route("/:id").delete(protected_middleware_1.protectedMiddleware, (0, allowedTo_middleware_1.allowedTo)(user_interface_1.Role.RootAdmin, user_interface_1.Role.AdminA, user_interface_1.Role.AdminB), offer_controller_1.deleteOffer);
exports.default = offerRouter;
